//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOperations")]
    public interface IOperations
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/SUM", ReplyAction="http://tempuri.org/IOperations/SUMResponse")]
        double SUM(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/SUM", ReplyAction="http://tempuri.org/IOperations/SUMResponse")]
        System.Threading.Tasks.Task<double> SUMAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/SUB", ReplyAction="http://tempuri.org/IOperations/SUBResponse")]
        double SUB(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/SUB", ReplyAction="http://tempuri.org/IOperations/SUBResponse")]
        System.Threading.Tasks.Task<double> SUBAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/DIV", ReplyAction="http://tempuri.org/IOperations/DIVResponse")]
        double DIV(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/DIV", ReplyAction="http://tempuri.org/IOperations/DIVResponse")]
        System.Threading.Tasks.Task<double> DIVAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/MUL", ReplyAction="http://tempuri.org/IOperations/MULResponse")]
        double MUL(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperations/MUL", ReplyAction="http://tempuri.org/IOperations/MULResponse")]
        System.Threading.Tasks.Task<double> MULAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IOperationsChannel : ServiceReference1.IOperations, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class OperationsClient : System.ServiceModel.ClientBase<ServiceReference1.IOperations>, ServiceReference1.IOperations
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OperationsClient() : 
                base(OperationsClient.GetDefaultBinding(), OperationsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOperations.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(EndpointConfiguration endpointConfiguration) : 
                base(OperationsClient.GetBindingForEndpoint(endpointConfiguration), OperationsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OperationsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OperationsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public double SUM(double a, double b)
        {
            return base.Channel.SUM(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SUMAsync(double a, double b)
        {
            return base.Channel.SUMAsync(a, b);
        }
        
        public double SUB(double a, double b)
        {
            return base.Channel.SUB(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SUBAsync(double a, double b)
        {
            return base.Channel.SUBAsync(a, b);
        }
        
        public double DIV(double a, double b)
        {
            return base.Channel.DIV(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DIVAsync(double a, double b)
        {
            return base.Channel.DIVAsync(a, b);
        }
        
        public double MUL(double a, double b)
        {
            return base.Channel.MUL(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MULAsync(double a, double b)
        {
            return base.Channel.MULAsync(a, b);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOperations))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOperations))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7138/CalService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OperationsClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOperations);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OperationsClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOperations);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOperations,
        }
    }
}
